### ISSUE TITLE
اپدیت

### ISSUE THREAD

**Issue by realartin** [SafaSafari/electrodar#1]
درود لطفا ریپو رو اپدیت کنید من حیف این رو دیر دیدم و اپ اش رو متاسفانه نصب کردم باید حالا کل سیستم رو اسکن کنم 😭

لطفا ریپو رو اپدیت کنید تا بتونیم سرور های جدید رو هم دریافت کنیم 🙏❤️

**Comment by SafaSafari** [comment]
عه نگفتم؟
آپدیت کردم کد رو =))

**Comment by w0l4i** [comment]
دمت گرم یعنی الان میشه سرور های رادار پلاس کلوز بتا که تو توییتر برات فرستادم رو در اورد ؟ دمت گرم لطف بزرگی کردی

**Comment by SafaSafari** [comment]
آره میشه =))

**Comment by w0l4i** [comment]
😍

**Comment by w0l4i** [comment]
> آره میشه =))

![image](https://github.com/SafaSafari/electrodar/assets/52799129/d5a84b78-ac4e-4b1b-a7cd-35c1ef8bcae5)

**Comment by w0l4i** [comment]
سرور های داخلی رو خروجی نمیده ! مثلا شماره 7 به بعد رو
